# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhoI0exCMx7bYEYDVYUdv9Fg9KKLsEc7
"""

import pandas as pd
baza={
    "FISH": ["Boymirzayev Alijon","Aminjonov Nurulloh","To'xtasinov Boynazar","Yusupjonov Muhsinjon","Mahmudova Nigora","Ahmmadjonova Muxlisa","Alijonov Ozodbek" ],
    "Yoshi":["14","13","11","12","15","10","11"],
    "Jinsi":["o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola","qiz bola","o'g'il bola"],
    "Maktab raqmi":["2","45","34","12","9","23","17"]

}
df=pd.DataFrame(baza)
print(df)

df.to_excel("baza.xlsx")

filtr=df.loc[df["Jinsi"]=="qiz bola"]
print(filtr)

filtr=df.loc[df["Jinsi"]=="o'g'il bola"]
print(filtr)

filtr=df.loc[(df["Yoshi"]>"12")&(df["Jinsi"]=="o'g'il bola")]
print(filtr)

filtr=df["Yoshi"].min()
print(filtr)